sensors:
  - id: 3da6d03bd42e41a93dc941bd5fd9351d
    sensor_type: IMU
    description: "Bosch BMI085 IMU"
    topic: /alphasense_driver_ros/imu
    sigmas:
      acc_bias_random_walk_noise_density: 0.0043
      acc_noise_density: 0.019
      gyro_bias_random_walk_noise_density: 0.000266
      gyro_noise_density: 0.019
    saturation_accel_max_mps2: 150
    saturation_gyro_max_radps: 7.5
    gravity_magnitude_mps2: 9.808083883386614


  - id: cabb23479caf7592b35518478a2fe08d
    sensor_type: ODOMETRY_6DOF
    description: "ROVIOLI in Odometry mode"
    topic: /odometry/maplab_odom_T_M_I

  - id: 9af2bac2a7c5fad79f09e49e3b96d87c
    sensor_type: NCAMERA
    description: "Alphasense Dev-Kit - 5 Cameras"
    topic: ""
    cameras:
      - camera:
          id: ca27b5000f15adb3c0da8ac6b729ff06
          sensor_type: CAMERA
          description: "0.4MP Mono Camera"
          topic: /alphasense_driver_ros/cam0
          line-delay-nanoseconds: 0
          image_height: 540
          image_width: 720
          type: pinhole
          intrinsics:
            rows: 4
            cols: 1
            data:
              - 350.4831235139715
              - 350.10097224389284
              - 345.2741039224713
              - 248.60977726525488
          distortion:
            type: equidistant
            parameters:
              rows: 4
              cols: 1
              data:
                - -0.038616930266761
                - -0.001017864366762166
                - -0.0010505629480572155
                - 5.958057565690519e-05

        T_B_C:
          rows: 4
          cols: 4
          data:
            - [-0.010397652184133632, 0.002270454146420686, 0.9999433653297707, 0.050014815850033034]
            - [-0.9999427667673746, -0.0025440594885076107, -0.010391869462572922, 0.04637904976425318]
            - [0.0025203211434270956, -0.9999941863827451, 0.0022967764466876317, -0.009598263721167621]
            - [0.0, 0.0, 0.0, 1.0]

extrinsics:
  - sensor_id: 3da6d03bd42e41a93dc941bd5fd9351d
    base_sensor_id: 3da6d03bd42e41a93dc941bd5fd9351d
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]
  - sensor_id: cabb23479caf7592b35518478a2fe08d
    base_sensor_id: 3da6d03bd42e41a93dc941bd5fd9351d
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id: 9af2bac2a7c5fad79f09e49e3b96d87c
    base_sensor_id: 3da6d03bd42e41a93dc941bd5fd9351d
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]
