server_config:
  map_folder:            "/tmp/euroc/maplab_server_map"
  resource_folder:       ""
  map_backup_interval_s: 300

  submap_commands:
    - "optvi --ba_num_iterations=20 --ba_enable_signal_handler=false"

  global_map_commands:
    - "aam"
    - "lc"
    - "optvi --ba_num_iterations 1 --ba_enable_signal_handler=false"
    - "elq --vi_map_landmark_quality_min_observers=2"

connection_config:
  - name:                euroc_mh_1
    topic:               "/euroc_mh_1/maplab_node/map_update_notification"
    ip:                  "localhost"
    user:                "mfehr"
  - name:                euroc_mh_2
    topic:               "/euroc_mh_2/maplab_node/map_update_notification"
    ip:                  "localhost"
    user:                "mfehr"
  - name:                euroc_mh_3
    topic:               "/euroc_mh_3/maplab_node/map_update_notification"
    ip:                  "localhost"
    user:                "mfehr"
  - name:                euroc_mh_4
    topic:               "/euroc_mh_4/maplab_node/map_update_notification"
    ip:                  "localhost"
    user:                "mfehr"
  - name:                euroc_mh_5
    topic:               "/euroc_mh_5/maplab_node/map_update_notification"
    ip:                  "localhost"
    user:                "mfehr"
