server_config:
  map_folder:            "/tmp/euroc/maplab_server_map"
  resource_folder:       ""
  map_backup_interval_s: 300

  submap_commands:
    - "optvi --ba_num_iterations=20 --ba_enable_signal_handler=false"

  global_map_commands:
    - "aam --lc_mission_baseframe_min_inlier_ratio=0.05 --lc_min_inlier_ratio=0.05 --lc_min_inlier_count=5 --lc_ransac_pixel_sigma=3"
    - "lc"
    - "optvi --ba_num_iterations 1 --ba_enable_signal_handler=false"
    - "elq --vi_map_landmark_quality_min_observers=2"

connection_config:
  - name:                euroc_mh_1
    topic:               "/transfolder/euroc_mh_1/folder_arrival_notification"
    ip:                  "localhost"
    user:                "none"
  - name:                euroc_mh_2
    topic:               "/transfolder/euroc_mh_2/folder_arrival_notification"
    ip:                  "localhost"
    user:                "none"
  - name:                euroc_mh_3
    topic:               "/transfolder/euroc_mh_3/folder_arrival_notification"
    ip:                  "localhost"
    user:                "none"
  - name:                euroc_mh_4
    topic:               "/transfolder/euroc_mh_4/folder_arrival_notification"
    ip:                  "localhost"
    user:                "none"
  - name:                euroc_mh_5
    topic:               "/transfolder/euroc_mh_5/folder_arrival_notification"
    ip:                  "localhost"
    user:                "none"
