server_config:
  map_folder:            "/tmp/maplab_server_node/combined_map"
  resource_folder:       "/tmp/maplab_server_node/combined_map_resources"
  map_backup_interval_s: 300

  submap_commands:
    - "lc"
    - "optvi --ba_num_iterations=20 --ba_enable_signal_handler=false"

  global_map_commands:
    - "lc"
    - "optvi --ba_num_iterations=3 --ba_enable_signal_handler=false"
    - "elq --vi_map_landmark_quality_min_observers=2"
    - "rbl"

connection_config:
  - name:                local_maplab_node
    topic:               "/maplab_node/map_update_notification"
    ip:                  "localhost"
    user:                ""
